src/controllers/service.controller.ts:61:28 - error TS2345: Argument of type '{ user: any; rating: any; comment: any; }' is not assignable to parameter of type '{ user: ObjectId; rating: number; comment: string; createdAt: Date; }'.   Property 'createdAt' is missing in type '{ user: any; rating: any; comment: any; }' but required in type '{ user: ObjectId; rating: number; comment: string; createdAt: Date; }'.
 61       service.reviews.push({
                               ~
 62         user: userId,
    ~~~~~~~~~~~~~~~~~~~~~
...
 64         comment,
    ~~~~~~~~~~~~~~~~
 65       });
    ~~~~~~~

  src/models/Service.ts:27:5
    27     createdAt: Date;
           ~~~~~~~~~
    'createdAt' is declared here.

    at createTSError (C:\Desktop\aman.com\Backend\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (C:\Desktop\aman.com\Backend\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (C:\Desktop\aman.com\Backend\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (C:\Desktop\aman.com\Backend\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (C:\Desktop\aman.com\Backend\node_modules\ts-node\src\index.ts:1617:30)
    at loadTS (node:internal/modules/cjs/loader:1826:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Desktop\aman.com\Backend\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1469:32)
    at Function._load (node:internal/modules/cjs/loader:1286:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14) {
  diagnosticCodes: [ 2339, 2345 ]
}
[nodemon] app crashed - waiting for file changes before starting...